# Generated by Django 4.2.5 on 2023-09-29 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0003_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="follower",
        ),
        migrations.AddField(
            model_name="profile",
            name="followers",
            field=models.ManyToManyField(
                related_name="followers_profile", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RemoveField(
            model_name="profile",
            name="following",
        ),
        migrations.AddField(
            model_name="profile",
            name="following",
            field=models.ManyToManyField(
                related_name="following_profile", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
